name: publish-docs

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Generate doc
        uses: seeebiii/redoc-cli-github-action@v10
        with:
          args: 'bundle openapi.yml -o dist/index.html --options.disableSearch --options.requiredPropsFirst --options.sortPropsAlphabetically'

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
